window.timelineData = [
    { month: '7月', emoji: '⭐', title: '星空下的约定', disabled: true,
        desc: '我们驱车到郊外看星星，躺在毯子上数着流星，你悄悄在我耳边说了那句让我红了脸的话。', date: '7月某个夜晚' },
    { month: '8月', emoji: '🍉', title: '甜蜜的日常', disabled: true,
        desc: '炎热的夏天，我们一起窝在空调房里吃西瓜追剧，最简单的小事，因为有你在都变得特别美好。', date: '8月' },
    { month: '9月', emoji: '📸', title: '拍了好多合照', disabled: true,
        desc: '那天阳光特别好，我们带着相机在城市里漫无目的地逛，拍下了无数张笑着的照片。', date: '9月' },
    { month: '10月', emoji: '🎃', title: '万圣节搞怪', disabled: true,
        desc: '你扮成可爱的南瓜怪，我笑到直不起腰。结束后我们捧着热可可走在落叶满地的街道上。', date: '10月31日' },
    { month: '11月', emoji: '🧣', title: '初冬的温暖', disabled: true,
        desc: '天气转凉，你把围巾分给我一半，我们靠在一起走在街灯下，呼出的白气交织在一起。', date: '11月' },
    { month: '12月', emoji: '🎄', title: '圣诞与新期待', disabled: true,
        desc: '一起装饰圣诞树，交换礼物，在零点钟声敲响时拥抱。感谢这一年有你，期待未来的每一年。', date: '12月25日' },
    { month: '1月', emoji: '💌', title: '新年第一面', disabled: true,
        desc: '元旦那天我们一起去看了烟花，在寒冬里握紧彼此的手，许下了新年的愿望。', date: '1月1日' },
    { month: '2月', emoji: '🌹', title: '情人节惊喜', disabled: true,
        desc: '你偷偷准备了一整天的惊喜，那束玫瑰和手写信，我至今珍藏在抽屉里。', date: '2月14日' },
    { month: '3月', emoji: '🌸', title: '春日踏青',
        desc: '樱花树下，我们并肩坐在长椅上，春风拂过，花瓣落在你的肩头，那一刻美得像画。', date: '3月某个周末' },
    { month: '4月', emoji: '🎵', title: '一起看演唱会',
        desc: '我们最喜欢的歌手终于来了！全场大合唱的时候，你转头看我的眼神让我心跳加速。', date: '4月中旬' },
    { month: '5月', emoji: '🍰', title: '你的生日月',
        desc: '这是我们在一起后你的第一个生日，我悄悄准备了一个月的惊喜，看到你笑的那一刻，一切都值了。', date: '5月' },
    { month: '6月', emoji: '🌊', title: '海边旅行',
        desc: '踩着细软的沙子，看着落日沉入海平面，你说希望时间就停在这一秒。', date: '6月10日' },
];
